esphome:
  name: esp-test

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "IaOmV6+5P6QTL9DAI0Mbp66DRSNeiUtlSiK5TGOtiNg="

ota:
  password: "68d92efa722f629aeba2c0ddac8eeaa6"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp-Test Fallback Hotspot"
    password: "Zxn2AtpvEiqr"

captive_portal:

binary_sensor:
  - platform: homeassistant
    name: "Esp Deep Sleep"
    entity_id: input_boolean.esp_deep_sleep 
    id: esp_deep_sleep
    publish_initial_state: true
    on_state:
      then:
        - lambda: !lambda |-
            if(x){
              id(esp_test_text).publish_state("Deep sleep on");
              id(deep_sleep_1).set_sleep_duration(30000);
              id(deep_sleep_1).begin_sleep(true);
            } else {
              id(esp_test_text).publish_state("Deep sleep off");         
              id(deep_sleep_1).prevent_deep_sleep();
            }

text_sensor:
  - platform: template
    name: esp_test_text
    id: esp_test_text

sensor:
  - platform: adc
    pin: VCC
    name: "esp_test_battery"
    accuracy_decimals: 2 

deep_sleep:
  run_duration: 30s
  id: deep_sleep_1
