
sensor:
  - platform: integration
    source: sensor.dishwasher_power
    name: dishwasher_energy
    unique_id: dishwasher_energy
    round: 2
    method: left
    unit_prefix: k

  - platform: history_stats
    name: dishwasher_runtime_today
    entity_id: sensor.dishwasher_running
    state: "True"
    type: time
    start: "{{ now().replace(hour=0, minute=0, second=0) }}"
    end: "{{ now() }}"

utility_meter:
  dishwasher_daily_energy:
    source: sensor.dishwasher_energy
    name: dishwasher_daily_energy
    unique_id: dishwasher_daily_energy
    cycle: daily

template:
  sensor:
    - name: dishwasher_power
      unique_id: dishwasher_power
      device_class: power
      state: >-
        {% if states('sensor.dishwasher_plug_power') | float(0) < 0 %}
          0
        {% else %}
          {{ states('sensor.dishwasher_plug_power') | float(0) }}
        {% endif %}
      unit_of_measurement: W

    - name: "Dishwasher running"
      unique_id : "dishwasher_running"
      state: "{{ states('sensor.dishwasher_power') | float(0) > 5 }}"
      
automation:
  - id: 'dishwasher_finished'
    alias: _Oppvaskmaskin ferdig
    description: ''
    trigger:
    - platform: state
      entity_id: sensor.dishwasher_running
      to: 'False'
      for: 00:00:30
      from: 'True'
    condition: []
    action:
    - service: tts.cloud_say
      data:
        entity_id: media_player.kjellerkontoret_speaker
        message: Oppvaskmaskinen er ferdig
        cache: true
    - service: notify.mobile_app_kb2003 #notify.mobile_app_ronnys_iphone
      data:
        message: Oppvaskmaskinen er ferdig
        title: The computer says
        data:
          ttl: 0
          priority: high
    # - service: notify.mobile_app_ronnys_iphone
    #   data:
    #     message: Oppvaskmaskinen er ferdig
    #     title: The computer says
    #     data:
    #       ttl: 0
    #       priority: high
    - service: notify.mobile_app_sbm_2016
      data:
        message: Oppvaskmaskinen er ferdig
        title: The computer says
    - service: notify.telia_box_loftet
      data:
        data:
          fontsize: large
          position: bottom-right
          duration: 10
          transparency: 50%
          image:
            url: !secret dishwasher_image_url
        message: Oppvaskmaskinen er ferdig
        title: The computer says
    - service: notify.telia_box_stue
      data:
        data:
          fontsize: large
          position: bottom-right
          duration: 10
          transparency: 50%
          image:
            url: !secret dishwasher_image_url
        message: Oppvaskmaskinen er ferdig
        title: The computer says
    mode: single