sensor:
  - platform: integration
    source: sensor.freezer_power
    name: freezer_energy
    unique_id: freezer_energy
    round: 2
    method: left
    unit_prefix: k

  - platform: history_stats
    name: freezer_runtime_today
    entity_id: sensor.freezer_running
    state: "True"
    type: time
    start: "{{ now().replace(hour=0, minute=0, second=0) }}"
    end: "{{ now() }}"

template:
  sensor:
    - name: freezer_power
      unique_id: freezer_power
      device_class: power
      state: >-
        {% if states('sensor.basement_freezer_plug_power') | float(0) < 0 %}
          0
        {% else %}
          {{ states('sensor.basement_freezer_plug_power') | float(0) }}
        {% endif %}
      unit_of_measurement: W

    - name: "Freezer running"
      unique_id : "freezer_running"
      state: "{{ states('sensor.freezer_power') | float(0) > 10 }}"

utility_meter:
  freezer_daily_energy:
    source: sensor.freezer_energy
    name: freezer_daily_energy
    unique_id: freezer_daily_energy
    cycle: daily