automation:
  - id: 'hall_basement_light_on'
    alias: _Kjellergang - Automatisk lys på
    description: ''
    trigger:
    - type: motion
      platform: device
      device_id: 3d74d5252ef3e9b00d830ca3be4d1fdd
      entity_id: binary_sensor.hall_basement_motion_occupancy
      domain: binary_sensor
    condition: []
    action:
    - choose:
      - conditions:
        - condition: time
          after: 02:00
          before: 06:00
        sequence:
        - service: light.turn_on
          data:
            transition: 2
            brightness_pct: 30
          target:
            entity_id:
            - light.hall_basement_light_switch
      default:
      - service: light.turn_on
        data:
          transition: 1
          brightness_pct: 65
        target:
          entity_id:
          - light.hall_basement_light_switch
    mode: single

  - id: 'hall_basement_light_off'
    alias: _Kjellergang - automatisk lys av
    description: ''
    trigger:
    - type: no_motion
      platform: device
      device_id: 3d74d5252ef3e9b00d830ca3be4d1fdd
      entity_id: binary_sensor.hall_basement_motion_occupancy
      domain: binary_sensor
      for:
        hours: 0
        minutes: 10
        seconds: 0
        milliseconds: 0
    - platform: time
      at: 01:00
    condition: []
    action:
    - choose:
      - conditions:
        - condition: time
          after: 01:00
          before: 06:00
        sequence:
        - service: light.turn_off
          target:
            entity_id:
            - light.hall_basement_light_switch
          data:
            transition: 1
      default:
      - service: light.turn_on
        data:
          transition: 2
          brightness_pct: 15
        target:
          entity_id:
            - light.hall_basement_light_switch
    mode: restart